name: Gradle Test

on:
  pull_request:
    branches:
      - main
 jobs:
 test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            java: [ adopt@1.11 ]
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up JDK ${{ matrix.java }}
            uses: actions/setup-java@v2
            with:
              java-version: ${{ matrix.java }}

          - name: Grant execute permission for gradlew
            run: chmod +x gradlew

          - name: Run Gradle Test
            run: ./gradlew test
