name: Gradle Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.202+8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8.0.202+8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and test with Gradle
        run: ./gradlew test